version: '3.8'
services: 
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8000:8000
        volumes: 
            - .:/app
        depends_on: 
            - db

    db:
        image: postgres:'latest’
        restart: always
        environment: 
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            POSTGRES_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root

        volumes: 
            - .dbdata:/var/lib/mysql
        ports: 
            - 5432:5432

       

